"""Constants for use in random character and dungeon generation."""

FIGHTER_NAMES = [
    "Alistair Goldleaf",
    "Anya Steelgaze",
    "Ariana Swiftarrow",
    "Baldric Stormcaller",
    "Brynn Thundershield",
    "Caelum Silentblade",
    "Cassius Blackthorn",
    "Darius Skyclad",
    "Elara Moonblade",
    "Eldric the Bold",
    "Evelyn Dawnseeker",
    "Fenrir Sunward",
    "Gareth Ironfist",
    "Gwendolyn Wolfheart",
    "Iris Whisperwind",
    "Jorin Wildheart",
    "Kaelen Darkwood",
    "Kendrick Flamebearer",
    "Leona Brightshield",
    "Lysander Shadowwalker",
    "Merek Stonecleaver",
    "Nadia Nightbreeze",
    "Orion Frostborne",
    "Rowan Stormbringer",
    "Seraphina Starlight",
    "Sylvana Starforge",
    "Thane Silverhelm",
    "Tristan Runeblade",
    "Varric Thunderhand",
    "Zephyr Ironsoul",
]


ELF_NAMES = [
    "Adran Highforest",
    "Aelar Galanodel",
    "Arannis Starflower",
    "Ariella Greenleaf",
    "Caelum Sunarrow",
    "Eiravel Xiloscient",
    "Elora Duskwalker",
    "Erevan Skyharrow",
    "Faelar Silverfrond",
    "Fenris Silversong",
    "Galinndan Evenwood",
    "Ilphelkiir Serpentsbane",
    "Isilme Moonshadow",
    "Lia Moonwhisper",
    "Nuala Nightbreeze",
    "Riveth Meliamne",
    "Rolen Oakenshield",
    "Sariel Dawnbrook",
    "Theren Nailo",
    "Ysora Brightstar",
]


CLERIC_NAMES = [
    "Alaric Peaceforged",
    "Anastasia Brightsoul",
    "Aurora Gracehand",
    "Bran Hearthmender",
    "Callista Faithsong",
    "Cassian Dawnwhisper",
    "Cedric Sageblessed",
    "Damaris Spiritheart",
    "Darius Lifebinder",
    "Elian Lightbringer",
    "Elowen Starhealer",
    "Ezra Stormcaller",
    "Finnian Soulkeeper",
    "Gideon Sunward",
    "Godric Holybrand",
    "Ione Truthseeker",
    "Kira Everlight",
    "Lucius Ironfaith",
    "Lydia Hearthward",
    "Maeve Starwatcher",
    "Mirabel Starfall",
    "Niamh Sunsong",
    "Orpheus Moonward",
    "Raphael Ironprayer",
    "Rowena Sageheart",
    "Serena Peaceweaver",
    "Silas Shadowbane",
    "Sylvester Nightingale",
    "Thalia Moonblessed",
    "Tristram Lightshield",
]


DWARF_NAMES = [
    "Audhild Strongheart",
    "Balin Ironhand",
    "Borin Ironfist",
    "Bram Coppervein",
    "Dagnal Stormforge",
    "Dorn Heavyhammer",
    "Eberk Alestout",
    "Elsa Axebrewer",
    "Fargrim Earthshield",
    "Greta Stonebreaker",
    "Harbek Goldfinder",
    "Helga Shieldmaiden",
    "Hilda Thunderforge",
    "Korbin Battlebeard",
    "Magni Silveraxe",
    "Orsik Flamebeard",
    "Runa Mountainbraid",
    "Sigrun Rockseeker",
    "Tilda Ironfoot",
    "Ulfgar Frostbeard",
]


THIEF_NAMES = [
    "Aria Moonmark",
    "Bram Slipknot",
    "Cade Thistleshank",
    "Corbin Blackcloak",
    "Dax Whisperwind",
    "Elara Starthief",
    "Eris Silentstep",
    "Finn Sleight",
    "Garrett Ironmask",
    "Isla Ghoststep",
    "Ivy Quickfoot",
    "Jasper Nightlock",
    "Lila Fleetshadow",
    "Lorcan Shadowhand",
    "Mara Softpocket",
    "Milo Swiftfingers",
    "Neve Shadowmere",
    "Nyx Lightfinger",
    "Rook Greygaze",
    "Seline Darkwhisper",
]


HALFLING_NAMES = [
    "Bella Burrows",
    "Bilbo Lightfoot",
    "Bramble Brushgather",
    "Bungo Thistleshanks",
    "Daisy Highhill",
    "Drogo Bramblethorn",
    "Esmerelda Butterchurn",
    "Finn Greenbottle",
    "Lily Greenhill",
    "Lobelia Applebloom",
    "Meriadoc Brandybuck",
    "Milo Underbough",
    "Norah Knotwise",
    "Perrin Goodbarrel",
    "Pippin Hilltopple",
    "Primrose Sandybanks",
    "Rosie Hardbiscuit",
    "Ruby Tealeaf",
    "Samwise Fairfoot",
    "Togo Weedwhacker",
]


MAGIC_USER_NAMES = [
    "Alaric Shadowcaster",
    "Ariadne Crystalgaze",
    "Athena Dreamweaver",
    "Azriel Sunwhisper",
    "Calista Starborn",
    "Cedric Stormcaller",
    "Circe Mysticmoon",
    "Draven Nightseer",
    "Emrys Voidwalker",
    "Evelyn Moonsinger",
    "Gaius Brightwand",
    "Iliana Frostfire",
    "Isolde Shadowspell",
    "Luna Spellbinder",
    "Lysandra Starweaver",
    "Magnus Darkweaver",
    "Orion Spellweaver",
    "Seraphina Flameheart",
    "Xander Highmage",
    "Zephyrus Lightbringer",
]


ADVENTURE_NAMES = [
    "Ancient Wizard's Riddle",
    "Arcane Shadows",
    "Cursed Glade Expedition",
    "Depths of Mysticism",
    "Echoes of Magic",
    "Enigma of Depths",
    "Forbidden Arcana",
    "Forgotten Citadel Journey",
    "Glofarnux's Legacy",
    "Glofarnux's Reckoning",
    "Haunted Forest Trek",
    "Hidden Realms",
    "Lich's Awakening",
    "Lost Glade Adventure",
    "Mystic Forest Quest",
    "Mystic Silence",
    "Subterranean Secrets",
    "Tale of the Mad Mage",
    "Twilight of Glofarnux",
    "Wizard's Lost Domain",
]

DUNGEON_NAMES = [
    "Ancient Wizard's Hold",
    "Arcane Underground",
    "Cursed Labyrinth",
    "Echoing Catacombs",
    "Enchanted Chambers",
    "Farnuxium Depths",
    "Forbidden Undercroft",
    "Forest Heart Dungeon",
    "Glofarnux's Bastion",
    "Glofarnux's Chambers",
    "Glofarnux's Tomb",
    "Lich's Hidden Stronghold",
    "Lost Wizard's Domain",
    "Mad Mage's Lair",
    "Mystic Grotto",
    "Mystic Hollows",
    "Mystic Maze",
    "Secluded Wizard's Keep",
    "Shadowed Halls",
    "Veiled Sanctum",
]
