"""Combat subpackage — state-driven tactical combat engine for osrlib.

Import public types from here::

    from osrlib.combat import CombatEngine, EncounterState, EventFormatter
"""

from osrlib.combat.conditions import (
    ActiveCondition,
    ConditionBehavior,
    ConditionTracker,
    CONDITION_REGISTRY,
)
from osrlib.combat.context import CombatContext, CombatSide, CombatantRef, MoraleState
from osrlib.combat.dice_service import BXDiceService, DiceService, FixedDiceService
from osrlib.combat.effects import (
    ApplyConditionEffect,
    ApplyModifierEffect,
    ConsumeItemEffect,
    ConsumeSlotEffect,
    DamageEffect,
    Effect,
    FleeEffect,
    HealEffect,
)
from osrlib.combat.modifiers import ActiveModifier, ModifiedStat, ModifierTracker
from osrlib.combat.actions import (
    ActionResult,
    CastSpellAction,
    CombatAction,
    FleeAction,
    MeleeAttackAction,
    RangedAttackAction,
    UseItemAction,
    THROWABLE_ITEMS,
)
from osrlib.combat.engine import CombatEngine, StepResult
from osrlib.combat.events import (
    ActionChoice,
    ActionRejected,
    AttackRolled,
    ConditionApplied,
    ConditionExpired,
    DamageApplied,
    HealingApplied,
    ItemUsed,
    ModifierApplied,
    ModifierExpired,
    EncounterEvent,
    EncounterFaulted,
    EncounterStarted,
    EntityDied,
    EntityFled,
    ForcedIntentApplied,
    ForcedIntentQueued,
    InitiativeRolled,
    MoraleChecked,
    NeedAction,
    RoundStarted,
    Rejection,
    RejectionCode,
    SavingThrowRolled,
    SpellCast,
    SpellSlotConsumed,
    SurpriseRolled,
    TurnQueueBuilt,
    TurnSkipped,
    TurnStarted,
    VictoryDetermined,
)
from osrlib.combat.formatter import ColorEventFormatter, EventFormatter
from osrlib.combat.intents import (
    ActionIntent,
    CastSpellIntent,
    FleeIntent,
    MeleeAttackIntent,
    RangedAttackIntent,
    UseItemIntent,
)
from osrlib.combat.serializer import EventSerializer
from osrlib.combat.spells import SpellDefinition, get_spell
from osrlib.combat.tactical_providers import RandomMonsterProvider, TacticalProvider
from osrlib.combat.views import CombatView, CombatantView
from osrlib.combat.state import EncounterLoopError, EncounterOutcome, EncounterState

__all__ = [
    "ActionIntent",
    "ActionChoice",
    "ActionResult",
    "ActionRejected",
    "ActiveCondition",
    "ApplyConditionEffect",
    "AttackRolled",
    "BXDiceService",
    "CastSpellAction",
    "CastSpellIntent",
    "ColorEventFormatter",
    "CombatAction",
    "CombatContext",
    "CombatEngine",
    "CombatSide",
    "CombatView",
    "CombatantRef",
    "CombatantView",
    "CONDITION_REGISTRY",
    "ConditionApplied",
    "ConditionBehavior",
    "ConditionExpired",
    "ConditionTracker",
    "ConsumeItemEffect",
    "ConsumeSlotEffect",
    "DamageEffect",
    "DamageApplied",
    "DiceService",
    "Effect",
    "EncounterEvent",
    "EncounterFaulted",
    "EncounterLoopError",
    "EncounterOutcome",
    "EncounterStarted",
    "EncounterState",
    "EntityDied",
    "EntityFled",
    "FleeAction",
    "FleeEffect",
    "HealEffect",
    "HealingApplied",
    "ItemUsed",
    "FleeIntent",
    "ForcedIntentApplied",
    "ForcedIntentQueued",
    "EventFormatter",
    "EventSerializer",
    "FixedDiceService",
    "InitiativeRolled",
    "MeleeAttackIntent",
    "MoraleChecked",
    "MoraleState",
    "NeedAction",
    "RangedAttackAction",
    "RangedAttackIntent",
    "RoundStarted",
    "Rejection",
    "RejectionCode",
    "SavingThrowRolled",
    "SpellCast",
    "SpellDefinition",
    "SpellSlotConsumed",
    "StepResult",
    "SurpriseRolled",
    "MeleeAttackAction",
    "RandomMonsterProvider",
    "TacticalProvider",
    "TurnQueueBuilt",
    "TurnSkipped",
    "THROWABLE_ITEMS",
    "TurnStarted",
    "UseItemAction",
    "UseItemIntent",
    "VictoryDetermined",
    "get_spell",
]
